/* Generated By:JavaCC: Do not edit this line. calculatorTreeConstants.java Version 5.0 */
public interface calculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=36cfecd383a17ec37844a79ae5bf19e9 (do not edit this line) */
