/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifier extends SimpleNode {

  public String val;
  public boolean method = false;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(ParserAST p, int id) {
    super(p, id);
  }

  @Override
  public String toString(String prefix) {
    String methodOption = (this.method) ? (" is method") : "";
    return super.toString(prefix) + ": " + this.val + methodOption; }

}
/* JavaCC - OriginalChecksum=8cc68f076904fa03c08bbbd0c4b1d8b7 (do not edit this line) */
