/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {

  public String parametherName;

  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(ParserAST p, int id) {
    super(p, id);
  }

  @Override
  public String toString(String prefix) {

    return super.toString(prefix) + ": " + this.parametherName;
  }

}
/* JavaCC - OriginalChecksum=e927b07d399429722bce5c9c2a37b786 (do not edit this line) */
