/* Generated By:JJTree: Do not edit this line. ASTNewObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewObject extends SimpleNode {

  public String val;

  public ASTNewObject(int id) {
    super(id);
  }

  public ASTNewObject(ParserAST p, int id) {
    super(p, id);
  }

  @Override
  public String toString(String prefix) { return super.toString(prefix) + ": " + this.val; }

}
/* JavaCC - OriginalChecksum=ede2b2f69469aac49323e026c608b62e (do not edit this line) */
